version: '3.8'

services:
  slack-bot:
    image: slack-bot:latest
    container_name: slack-bot
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "nohup python -m src.bot_main > /app/logs/bot_main.log 2>&1 &"
    restart: always
