name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # 當推送到主分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
    
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ubuntu/my_project/slack_bot_demo  # EC2 上程式的路徑
          git pull origin main       
          
          source ~/venv/bin/activate # 激活虛擬環境         
          PID=$(pgrep -f 'python bot_main.py') # 檢查是否有正在運行的 bot_main.py 進程            
          
          if [ -n "$PID" ]; then
              echo "Found running process with PID $PID. Killing it..."
              kill "$PID"
          else
              echo "No running process found."
          fi
          
          nohup python bot_main.py > bot_main.log 2>&1 &
          
          deactivate
        EOF
